# configure your datasource
quarkus.datasource.db-kind=postgresql

quarkus.hibernate-orm.schema-management.strategy=none
quarkus.hibernate-orm.validate-in-dev-mode=false

quarkus.http.port=8082
quarkus.grpc.server.use-separate-server=true
quarkus.grpc.server.port=9090

# Liquibase minimal config properties
quarkus.liquibase.migrate-at-start=true
quarkus.liquibase.change-log=db/main-changelog.xml

scheduler.customer-inactive.max-period=4h
scheduler.customer-inspection.interval=1m